GET http://localhost:4000/users

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "sato", 
    "password": "123"
}

###
//login
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "sato", 
    "password": "123" 
}

